<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260307220820 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cliente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(30) DEFAULT NULL, contato VARCHAR(35) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE orcamento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(120) DEFAULT NULL, qtd NUMERIC(10, 0) DEFAULT NULL, valor_total NUMERIC(10, 2) DEFAULT NULL, data TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id_servico_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4B1DD46D276BC955 ON orcamento (id_servico_id)');
        $this->addSql('CREATE TABLE servico (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(150) DEFAULT NULL, detalhe TEXT DEFAULT NULL, preco VARCHAR(20) DEFAULT NULL, foto TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE orcamento ADD CONSTRAINT FK_4B1DD46D276BC955 FOREIGN KEY (id_servico_id) REFERENCES servico (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE orcamento DROP CONSTRAINT FK_4B1DD46D276BC955');
        $this->addSql('DROP TABLE cliente');
        $this->addSql('DROP TABLE orcamento');
        $this->addSql('DROP TABLE servico');
    }
}
